
MAX_WIDTH = 210
MAX_HEIGHT = 60

POPUP_MARGIN_X = 20
POPUP_MARGIN_Y = 4
POPUP_WIDTH = (2 * MAX_WIDTH // 3) - 2 * POPUP_MARGIN_X
POPUP_HEIGHT = MAX_HEIGHT - 2 * POPUP_MARGIN_Y

DEFAULT_DATA_DIRECTORY = 'data'
DEFAULT_CHARACTER_PATH = 'character.hjson'
DEFAULT_CAMPAIGN_DB_PATH = 'campaign.hjson'
